disabled_rules: # rule identifiers to exclude from running
    - trailing_comma
    - todo

opt_in_rules: # some rules are only opt-in
    - closure_end_indentation
    - explicit_init
    - vertical_parameter_alignment_on_call

excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - DerivedData
    - Pods

line_length:
    warning: 150
    error: 200
    ignores_urls: true

file_length:
    warning: 600
    error: 1000

cyclomatic_complexity:
    ignores_case_statements: true

type_name:
    min_length: 3 # only warning
    max_length: # warning and error
        warning: 65
        error: 75
identifier_name:
    min_length: # only min_length
        error: 3 # only error
    max_length: # warning and error
        warning: 65
        error: 75
    excluded: # excluded via string array
# see https://github.com/realm/SwiftLint/issues/1424 for !str explanation
        - !str id
        - !str y
        - !str x
        - !str in
        - !str to
        - !str up
        - !str at
        - !str i
        - !str r
        - !str g
        - !str b
        - !str vm
        - !str vc
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

