# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Marvel Characters' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Marvel Characters
    pod 'Firebase/Analytics'
    pod 'Fabric', '~> 1.10.2'
    pod 'Crashlytics', '~> 3.13.4'

  target 'Marvel CharactersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Marvel CharactersUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
