stages:
  - prepare
  - build
  - test

Prepare:
  stage: prepare
  script:
    - cd Marvel\ Characters
    - carthage bootstrap --platform iOS
  artifacts:
    paths:
      - Marvel\ Characters/Carthage/Build/iOS/*.framework
  cache:
    paths:
      - Marvel\ Characters/Carthage
  tags:
    - macOS

Build:
  stage: build
  script:
    - cd Marvel\ Characters
    - mkdir DerivedData
    - xcodebuild build -project "Marvel Characters.xcodeproj" \
            -scheme "Marvel Characters" \
            -derivedDataPath ./DerivedData \
            CODE_SIGNING_ALLOWED=NO |
            tee -a ./DerivedData/xcodebuild.log | 
            xcpretty
  artifacts:
    paths:
      - Marvel\ Characters/DerivedData/
  dependencies:
    - Prepare
  tags:
    - macOS
    
Test:
  stage: test
  script:
    - cd Marvel\ Characters
    - xcodebuild test \
            -project "Marvel Characters.xcodeproj" \
            -scheme "Marvel Characters" \
            -derivedDataPath ./DerivedData \
            -enableCodeCoverage YES \
            -destination "platform=iOS Simulator,name=iPhone 6" | 
            tee -a ./DerivedData/xcodebuild.log | 
            xcpretty --color
  #coverage: '/Code coverage: \d+\.\d+/'
  retry:
    max: 2
  dependencies:
    - Build
  tags:
    - macOS
    - iPhone6_simulator_available
