default:
  before_script:
   - cd Marvel\ Characters


cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - Marvel\ Characters/Carthage/Checkouts
    - Marvel\ Characters/Carthage/Build/*.version
    - Marvel\ Characters/Carthage/Build/iOS/*.framework
    - Marvel\ Characters/Pods

cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - Marvel\ Characters/DerivedData

stages:
  - setup
  - build
  - test
  
Prepare:
  stage: setup
  script:
    - carthage bootstrap --platform iOS --cache-builds
    - pod install

  retry:
    max: 2

  only:
    refs:
     - tags
     - merge_requests
     - branches

  tags:
    - macOS
    - iPhone6_simulator_available

BuildForTesting:
  stage: build
    
  script:
    - mkdir DerivedData
    - xcodebuild build-for-testing -workspace "Marvel Characters.xcworkspace" -scheme "Marvel Characters" -derivedDataPath ./DerivedData CODE_SIGNING_ALLOWED=NO -enableCodeCoverage YES -destination "platform=iOS Simulator,name=iPhone 6" | tee ./DerivedData/xcodebuild.log | xcpretty --color

  after_script:
   - rm -rf Carthage
   - rm -rf Pods

  only:
    refs:
     - tags
     - merge_requests
     - branches 
  
  artifacts:
    when: on_failure
    paths:
      - Marvel\ Characters/DerivedData/xcodebuild.log

  dependencies:
     - Prepare

  tags:
    - macOS
    - iPhone6_simulator_available

Test:
  stage: test

  script:
    - xcodebuild test-without-building -workspace "Marvel Characters.xcworkspace" -scheme "Marvel Characters" -derivedDataPath ./DerivedData CODE_SIGNING_ALLOWED=NO -enableCodeCoverage YES -destination "platform=iOS Simulator,name=iPhone 6" | xcpretty --color -r junit
    - xcrun xccov view DerivedData/Logs/Test/*.xcresult/*_Test/*.xccovreport | grep '.app' | head -1 | perl -pe 's/.+?(\d+\.\d+%).+/\1/'
 
  coverage: '/\d+\.\d+%/'

  retry:
    max: 1

  artifacts:
    when: on_success
    reports:
      junit: Marvel\ Characters/build/reports/junit.xml

  only:
    refs:
     - develop
     - master
     - tags
     - merge_requests

  dependencies:
     - BuildForTesting

  tags:
    - macOS
    - iPhone6_simulator_available
