before_script:
  #- sudo /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  #- brew install Carthage
  #- sudo gem install xcpretty
  - cd Marvel\ Characters
  - carthage bootstrap --platform iOS
  
stages:
  - build_test

build_project:
  stage: build_test
  script:
    - /usr/bin/xcodebuild clean -project Marvel\ Characters.xcodeproj -scheme Marvel\ Characters | /usr/local/bin/xcpretty -s
    - /usr/bin/xcodebuild test  -project Marvel\ Characters.xcodeproj -scheme Marvel\ Characters -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.2'  | xcpretty -s --test --color
  tags:
    - Xcode-10.2.1
    - macOSMojave