default:
  before_script:
   - cd Marvel\ Characters
  after_script:
   - rm -rf Marvel\ Characters/DerivedData

stages:
  - setup
  - build
  - test
  
Prepare:
  stage: setup
  script:
    - carthage bootstrap --platform iOS --cache-builds
    - pod install
  
  cache:
   key: carthage
   paths:
    - Marvel\ Characters/Carthage/Checkouts
    - Marvel\ Characters/Carthage/Build/*.version
    - Marvel\ Characters/Carthage/Build/iOS/*.framework
    - Marvel\ Characters/Pods

  tags:
    - macOS
    - iPhone6_simulator_available

Build:
  stage: build
  script:
    - mkdir DerivedData
    - xcodebuild build -workspace "Marvel Characters.xcworkspace" -scheme "Marvel Characters" -derivedDataPath ./DerivedData CODE_SIGNING_ALLOWED=NO | tee ./DerivedData/xcodebuild.log | xcpretty
    - rm -rf Carthage
    - cp DerivedData/xcodebuild.log xcodebuild.log
  artifacts:
    when: on_failure
    paths:
      - Marvel\ Characters/xcodebuild.log
  except:
    refs:
     - develop
     - master
     - tags
     - merge_requests
  dependencies:
    - Prepare
  cache:
    key: carthage
    paths:
      - Marvel\ Characters/Carthage/Build/iOS/*.framework
      - Marvel\ Characters/Pods
    policy: pull
  tags:
    - macOS
    - iPhone6_simulator_available

Test:
  stage: test
  script:
    - mkdir DerivedData
    - xcodebuild test -workspace "Marvel Characters.xcworkspace" -scheme "Marvel Characters" -derivedDataPath ./DerivedData CODE_SIGNING_ALLOWED=NO -enableCodeCoverage YES -destination "platform=iOS Simulator,name=iPhone 6" | tee ./DerivedData/xcodebuild.log | xcpretty --color -r junit
    - xcrun xccov view DerivedData/Logs/Test/*.xcresult/*_Test/*.xccovreport | grep '.app' | head -1 | perl -pe 's/.+?(\d+\.\d+%).+/\1/'
    - rm -rf Carthage
  coverage: '/\d+\.\d+%/'
  retry:
    max: 1
  artifacts:
    reports:
      junit: Marvel\ Characters/build/reports/junit.xml
  only:
    refs:
     - develop
     - master
     - tags
     - merge_requests
  dependencies:
    - Prepare
  cache:
    key: carthage
    paths:
     - Marvel\ Characters/Carthage/Build/iOS/*.framework
     - Marvel\ Characters/Pods
    policy: pull
  tags:
    - macOS
    - iPhone6_simulator_available
