before_script:
  #- sudo /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  #- brew install Carthage
  #- sudo gem install xcpretty
  - cd Marvel\ Characters
  - carthage bootstrap --platform iOS
  
stages:
  - test

build_project:
  stage: test
  script:
    - xcodebuild \
            -project "Marvel Characters.xcodeproj" \
            -scheme "Marvel Characters" \
            -derivedDataPath ./DerivedData \
            -enableCodeCoverage YES \
            clean build test clean \
            CODE_SIGNING_ALLOWED=NO \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 6" \
            | tee ./DerivedData/xcodebuild.log | xcpretty --color --test
  
  tags:
    - macOS
    - iPhone6_simulator_available