stages:
  - prepare
  - build
  - test
  - clean

prepare_project:
  stage: prepare
  script:
    - cd Marvel\ Characters
    - carthage bootstrap --platform iOS
  artifacts:
    paths:
      - Marvel\ Characters/Carthage/
  tags:
    - macOS

clean_project:
  stage: clean
  script:
    - cd Marvel\ Characters
    - xcodebuild clean | xcpretty
  tags:
    - macOS

build_project:
  stage: build
  script:
    - cd Marvel\ Characters
    - rm -rf DerivedData
    - mkdir DerivedData
    - xcodebuild clean build \
            -project "Marvel Characters.xcodeproj" \
            -scheme "Marvel Characters" \
            -derivedDataPath ./DerivedData \
            CODE_SIGNING_ALLOWED=NO | 
            tee -a ./DerivedData/xcodebuild.log | 
            xcpretty
  artifacts:
    paths:
      - Marvel\ Characters/DerivedData/
  dependencies:
    - prepare_project
  tags:
    - macOS
    
test_project:
  stage: test
  script:
    - cd Marvel\ Characters
    - xcodebuild test \
            -project "Marvel Characters.xcodeproj" \
            -scheme "Marvel Characters" \
            -derivedDataPath ./DerivedData \
            -enableCodeCoverage YES \
            -destination "platform=iOS Simulator,name=iPhone 6" | 
            tee -a ./DerivedData/xcodebuild.log | 
            xcpretty --color
  #coverage: '/Code coverage: \d+\.\d+/'
  retry:
    max: 2
  dependencies:
    - build_project
  tags:
    - macOS
    - iPhone6_simulator_available
