stages:
  - prepare
  - clean
  - build
  - test
  - clean

prepare_project:
  stage: prepare
  script:
    - cd Marvel\ Characters
    - rm -rf DerivedData
    - mkdir DerivedData
    - carthage bootstrap --platform iOS
  tags:
    - macOS

clean_project:
  stage: clean
  script:
    - xcodebuild clean | xcpretty
  tags:
    - macOS

build_project:
  stage: build
  script:
    - xcodebuild build \
            -project "Marvel Characters.xcodeproj" \
            -scheme "Marvel Characters" \
            -derivedDataPath ./DerivedData \
            CODE_SIGNING_ALLOWED=NO | 
            tee -a ./DerivedData/xcodebuild.log | 
            xcpretty
  tags:
    - macOS
    
test_project:
  stage: test
  script:
    - xcodebuild test \
            -project "Marvel Characters.xcodeproj" \
            -scheme "Marvel Characters" \
            -derivedDataPath ./DerivedData \
            -enableCodeCoverage YES \
            -destination "platform=iOS Simulator,name=iPhone 6" | 
            tee -a ./DerivedData/xcodebuild.log | 
            xcpretty --color
  tags:
    - macOS
    - iPhone6_simulator_available