before_script:
  #- sudo /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  #- brew install Carthage
  #- sudo gem install xcpretty
  - cd Marvel\ Characters
  - carthage bootstrap --platform iOS
  
stages:
  - clean
  - build
  - test
  - clean

clean_project:
  stage: clean
  script:
    - xcodebuild clean | xcpretty
    - rm -rf DerivedData
    - mkdir DerivedData
  tags:
    - macOS
build_project:
  stage: build
  script:
    - xcodebuild build \
            -project "Marvel Characters.xcodeproj" \
            -scheme "Marvel Characters" \
            -derivedDataPath ./DerivedData \
            CODE_SIGNING_ALLOWED=NO | 
            tee -a ./DerivedData/xcodebuild.log | 
            xcpretty
  tags:
    - macOS
test_project:
  stage: test
  script:
    - xcodebuild test \
            -project "Marvel Characters.xcodeproj" \
            -scheme "Marvel Characters" \
            -derivedDataPath ./DerivedData \
            -enableCodeCoverage YES \
            -destination "platform=iOS Simulator,name=iPhone 6" | 
            tee -a ./DerivedData/xcodebuild.log | 
            xcpretty --color
  tags:
    - macOS
    - iPhone6_simulator_available