default:
  before_script:
   - cd Marvel\ Characters

stages:
  - setup
  - build
  - test
  
Prepare:
  stage: setup
  script:
    - carthage bootstrap --platform iOS --cache-builds
    - pod install
     
  cache:
   key: carthage
   paths:
    - Marvel\ Characters/Carthage/Checkouts
    - Marvel\ Characters/Carthage/Build/*.version
    - Marvel\ Characters/Carthage/Build/iOS/*.framework
    - Marvel\ Characters/Pods

  retry:
    max: 2

  tags:
    - macOS
    - iPhone6_simulator_available

Build:
  stage: build

  before_script:
    - mkdir DerivedData

  script:
    - xcodebuild build-for-testing -workspace "Marvel Characters.xcworkspace" -scheme "Marvel Characters" -derivedDataPath ./DerivedData CODE_SIGNING_ALLOWED=NO -enableCodeCoverage YES -destination "platform=iOS Simulator,name=iPhone 6" | tee ./DerivedData/xcodebuild.log | xcpretty --color

  after_script:
   - rm -rf Carthage
   - rm -rf Pods
  
  artifacts:
    when: on_failure
    paths:
      - Marvel\ Characters/DerivedData/xcodebuild.log

  dependencies:
     - Prepare

  cache:
    key: carthage
    paths:
      - Marvel\ Characters/Carthage/Build/iOS/*.framework
      - Marvel\ Characters/Pods
    policy: pull

  cache:
    key: derivedData
    paths:
      - Marvel\ Characters/DerivedData

  tags:
    - macOS
    - iPhone6_simulator_available

Test:
  stage: test

  before_script:
    - mkdir DerivedData

  script:
    - xcodebuild build-for-testing -workspace "Marvel Characters.xcworkspace" -scheme "Marvel Characters" -derivedDataPath ./DerivedData CODE_SIGNING_ALLOWED=NO -enableCodeCoverage YES -destination "platform=iOS Simulator,name=iPhone 6" | tee ./DerivedData/xcodebuild.log | xcpretty --color

  after_script:
    - rm -rf Marvel\ Characters/DerivedData
   
  script:
    - xcodebuild test-without-building -workspace "Marvel Characters.xcworkspace" -scheme "Marvel Characters" -derivedDataPath ./DerivedData CODE_SIGNING_ALLOWED=NO -enableCodeCoverage YES -destination "platform=iOS Simulator,name=iPhone 6" | xcpretty --color -r junit
    - xcrun xccov view DerivedData/Logs/Test/*.xcresult/*_Test/*.xccovreport | grep '.app' | head -1 | perl -pe 's/.+?(\d+\.\d+%).+/\1/'
  
  coverage: '/\d+\.\d+%/'

  retry:
    max: 1

  artifacts:
    when: on_success
    reports:
      junit: Marvel\ Characters/build/reports/junit.xml

  only:
    refs:
     - develop
     - master
     - tags
     - merge_requests

  dependencies:
     - build

  cache:
    key: derivedData
    paths:
      - Marvel\ Characters/DerivedData
    policy: pull

  tags:
    - macOS
    - iPhone6_simulator_available
