before_script:
  #- sudo /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  #- brew install Carthage
  #- sudo gem install xcpretty
  - cd Marvel\ Characters
  - carthage bootstrap --platform iOS

stages:
  - test

Testing:
  stage: test
  script:
    - mkdir DerivedData
    - xcodebuild clean build test \
            -project "Marvel Characters.xcodeproj" \
            -scheme "Marvel Characters" \
            -derivedDataPath ./DerivedData \
            -enableCodeCoverage YES \
            CODE_SIGNING_ALLOWED=NO \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 6" | 
            tee ./DerivedData/xcodebuild.log | 
            xcpretty --color
  tags:
    - macOS
    - iPhone6_simulator_available