before_script:
  #- sudo /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  #- brew install Carthage
  #- sudo gem install xcpretty
  #- npm install ios-sim -g
  - cd Marvel\ Characters
  - carthage bootstrap --platform iOS
  
stages:
  - test

build_project:
  stage: test
  script:
    - xcodebuild clean -scheme "Marvel Characters" | xcpretty -s
    - xcodebuild test -scheme "Marvel Characters" -destination "platform=iOS Simulator,name=iPhone 6s,OS=12.0" | xcpretty -s --test --color
  
  tags:
    - macOS