stages:
  - prepare
  - test

Prepare:
  stage: prepare
  script:
    - cd Marvel\ Characters
    - carthage bootstrap --platform iOS
  artifacts:
    paths:
      - Marvel\ Characters/Carthage/Build/iOS/*.framework
  tags:
    - macOS

Test:
  stage: test
  script:
    - cd Marvel\ Characters
    - mkdir DerivedData
    - xcodebuild test -project "Marvel Characters.xcodeproj" -scheme "Marvel Characters" -derivedDataPath ./DerivedData CODE_SIGNING_ALLOWED=NO -enableCodeCoverage YES -destination "platform=iOS Simulator,name=iPhone 6" | tee ./DerivedData/xcodebuild.log | xcpretty --color
    - xcrun xccov view DerivedData/Logs/Test/*.xcresult/*_Test/*.xccovreport | grep '.app' | head -1 | perl -pe 's/.+?(\d+\.\d+%).+/\1/'
  coverage: '/Code coverage: \d+\.\d+%/'
  retry:
    max: 2
  artifacts:
    paths:
      - Marvel\ Characters/DerivedData/xcodebuild.log
  dependencies:
    - Prepare
  tags:
    - macOS
    - iPhone6_simulator_available
